ProfileNum = input("What is this profile Number :")
nickname = input("What nickname do you want to give this Profile?:")
firstname= input("What is your First name?:")
lastname= input("what is your last name?:")
Phname= input("What is your PhoneticName, Press Enter to Skip:")
Phlastname= input("what is your PhoneticLastName, Press Enter to Skip:")
phonenumber = input("What is the first 6 Numbers of your phone number Followed by {random4}   EXAMPLE        123456{random4}:")
CardType= input("Enter Card Type: Visa, Americanexpress, Discover, or Mastercard MUST BE SPELLED RIGHT AND ALL CAPITAL:")
CardNum= input("Enter your entire Card Number")
Cardcvv= input("Enter your card CVV (3 Numbers on the back):")
ExpirationMonth= input("Enter your Card Expiration Month, Example (03 for March or 10 for October):")
ExpirationYear= input("Enter Expiration Year, Example (2022):")
Address1= input("Enter your Address for line 1 (only street name and Number):")
Address2= input("Enter your Address for line 2 if Required:")
Address3= input("Enter you Address for line 3 if Required:")
City= input("Enter your City:")
State= input("Input your State **The state has to have the 2 abbreviated letters for US. ** EXAMPLE California is CA **:")
Country= input("What Country are you in? *Example US,UK/GB*:")
Postal= input("What is your postal Code or Zip Code?")
print("PROFILE LAYOUT**************")
print("id,nickName,firstName,lastName,phoneticName,phoneticSurname,phoneNumber,cardType,cardNumber,cardCVV,expireMonth,expireYear,address1,address2,address3,city,state,country,postal")
print("Your Profile BELOW")
profileinputs =(ProfileNum +','+ nickname +','+ firstname +','+ lastname +','+ Phname +','+ Phlastname +','+ phonenumber +','+ CardType +','+ CardNum +','+ Cardcvv +','+ ExpirationMonth +','+ ExpirationYear +','+ Address1 +','+ Address2 +','+ Address3 +','+ City +','+ State +','+ Country +','+ Postal +',')

print('  _____                                 _             _ ')
print(' / ____|                               | |           | |')
print('| |  __   ___  _ __    ___  _ __  __ _ | |_  ___   __| |')
print("| | |_ | / _ \| '_  \ / _ \/ '__|/ _` || __|/ _ \ / _` |")
print('| |__| ||  __/| | | ||  __/| |  | (_| || |_|  __/| (_| |')
print(' \_____| \___||_| |_| \___||_|   \__,_| \__|\___| \__,_|')


filename= input("Save File as (((Example Profile.txt)))")
f = open(filename,'a')

f.write(profileinputs)
